"""Import all models so Alembic can discover them."""

from app.models.base import Base
from app.models.cms import WebsiteProductContent, WebsiteProductImage
from app.models.foundations import (
    Facility,
    ProductCategory,
    RecipeCategory,
    RunStatus,
    SalesChannel,
    StorageLocation,
    Unit,
    UnitConversion,
)
from app.models.identity import (
    AuditLog,
    Role,
    User,
    UserMfa,
    UserRecoveryCode,
    UserRefreshToken,
    UserRole,
)
from app.models.inventory import (
    IngredientInventory,
    IngredientLot,
    InventoryTransaction,
    ProductionRunIngredientConsumption,
    ProductLot,
    Supplier,
)
from app.models.production import (
    ApiIdempotencyKey,
    ProductionRun,
    ProductionRunCode,
    ProductionRunDeviation,
    ProductionRunDistribution,
    ProductionRunIngredient,
    ProductionRunQualityLog,
    QualityMetricType,
    QualityTemplate,
    QualityTemplateItem,
    ProductType,
    RunAttachment,
    RunMaterial,
)
from app.models.products import (
    Attachment,
    AttachmentLink,
    Product,
    ProductComplianceProfile,
    Sale,
    ScheduledProcessDocument,
)
from app.models.qc import (
    QcPlan,
    QcPlanRequirement,
    RunQcEntry,
)
from app.models.recipes import (
    Ingredient,
    Item,
    Recipe,
    RecipeVersion,
    RecipeVersionIngredient,
    RecipeVersionStep,
)

__all__ = [
    "Base",
    "AuditLog",
    "ApiIdempotencyKey",
    "Attachment",
    "AttachmentLink",
    "Facility",
    "Ingredient",
    "IngredientInventory",
    "IngredientLot",
    "InventoryTransaction",
    "Item",
    "Product",
    "ProductCategory",
    "ProductComplianceProfile",
    "ProductLot",
    "ProductType",
    "ProductionRun",
    "ProductionRunCode",
    "ProductionRunDeviation",
    "ProductionRunDistribution",
    "ProductionRunIngredient",
    "ProductionRunIngredientConsumption",
    "ProductionRunQualityLog",
    "QcPlan",
    "QcPlanRequirement",
    "QualityMetricType",
    "QualityTemplate",
    "QualityTemplateItem",
    "Recipe",
    "RecipeCategory",
    "RecipeVersion",
    "RecipeVersionIngredient",
    "RecipeVersionStep",
    "Role",
    "RunAttachment",
    "RunMaterial",
    "RunQcEntry",
    "RunStatus",
    "Sale",
    "SalesChannel",
    "ScheduledProcessDocument",
    "StorageLocation",
    "Supplier",
    "Unit",
    "UnitConversion",
    "User",
    "UserMfa",
    "UserRecoveryCode",
    "UserRefreshToken",
    "UserRole",
    "WebsiteProductContent",
    "WebsiteProductImage",
]
